name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set environment variables
      run: |
        source <(curl -sL https://github.com/aem-design/aemdesign-docker/releases/latest/download/get_config.sh)
        source <(curl -sL https://github.com/aem-design/aemdesign-docker/releases/latest/download/get_version.sh)
    - name: build jackrabbit
      run: |
        git clone https://github.com/aem-design/jackrabbit.git
        cd jackrabbit
        git checkout feature/enable-insecure-https-host
        mvn clean package install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -Dbaseline.skip=true
        cd ..
    - name: build jackrabbit-filevault
      run: |
        git clone https://github.com/aem-design/jackrabbit-filevault.git
        cd jackrabbit-filevault
        git checkout feature/enable-insecure-https-host
        mvn clean package -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -Dbaseline.skip=true
        cd vault-cli/target
        unzip vault-cli-3.4.1-SNAPSHOT-bin.zip
        cd ../../..
    - name: Check Jenkins Latest version
      run: |
        sudo apt-get -y install libxml2-utils
        export JENKINS_VERSION=$(wget -q -O - http://mirrors.jenkins.io/war-stable/ | xmllint --html --xpath "//table/tr[position() = (last() - 2)]/td[2]/a/text()" - | sed -e 's/[^0-9\.]//g')
        export RELEASE_DATE=$(wget -q -O - http://mirrors.jenkins.io/war-stable/ | xmllint --html --xpath "//table/tr[position() = (last() - 2)]/td[3]/text()" - | sed -n 's/\([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\).*/\1/p')
    - name: Build Jeknins docker image
      run: |
        echo $IMAGE:$IMAGE_VERSION  $JENKINS_VERSION
        docker build --pull -t $IMAGE:$IMAGE_VERSION --build-arg JENKINS_VERSION=$JENKINS_VERSION .
        echo test, and deploy your project.
